-- Protect360 Database and Schema Setup
CREATE DATABASE IF NOT EXISTS PROTECT360_DB COMMENT='Protect360 AI — Customer 360 and Next Best Action';

CREATE SCHEMA IF NOT EXISTS PROTECT360_DB.BRONZE COMMENT='Raw ingestion layer';
CREATE SCHEMA IF NOT EXISTS PROTECT360_DB.SILVER COMMENT='Cleaned and enriched layer';
CREATE SCHEMA IF NOT EXISTS PROTECT360_DB.GOLD COMMENT='Customer 360 and next-best-action layer';
CREATE SCHEMA IF NOT EXISTS PROTECT360_DB.ML COMMENT='Feature store and model metadata';
CREATE SCHEMA IF NOT EXISTS PROTECT360_DB.GOVERNANCE COMMENT='Audit, quality, and consent';
