-- Protect360 Warehouses
CREATE WAREHOUSE IF NOT EXISTS INGEST_WH    WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60  AUTO_RESUME=TRUE COMMENT='Data ingestion pipelines';
CREATE WAREHOUSE IF NOT EXISTS TRANSFORM_WH WAREHOUSE_SIZE='SMALL'  AUTO_SUSPEND=120 AUTO_RESUME=TRUE COMMENT='Dynamic Table refreshes and dbt transforms';
CREATE WAREHOUSE IF NOT EXISTS CORTEX_WH    WAREHOUSE_SIZE='SMALL'  AUTO_SUSPEND=60  AUTO_RESUME=TRUE COMMENT='Snowflake Cortex AI functions';
CREATE WAREHOUSE IF NOT EXISTS ML_WH        WAREHOUSE_SIZE='MEDIUM' AUTO_SUSPEND=60  AUTO_RESUME=TRUE COMMENT='ML training and batch scoring';
CREATE WAREHOUSE IF NOT EXISTS APP_WH       WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60  AUTO_RESUME=TRUE COMMENT='Streamlit in Snowflake app queries';
