-- Protect360 Role-Based Access Control

-- Roles
CREATE ROLE IF NOT EXISTS P360_ADMIN COMMENT='Full access to all Protect360 objects';
CREATE ROLE IF NOT EXISTS P360_ENGINEER COMMENT='Read/write bronze, silver, gold, ml';
CREATE ROLE IF NOT EXISTS P360_ML_ENGINEER COMMENT='ML engineers: read Silver/Gold, read/write ML schema, use ML_WH and CORTEX_WH';
CREATE ROLE IF NOT EXISTS P360_APP_USER COMMENT='Streamlit app end users: read Gold tables and views, use APP_WH';
CREATE ROLE IF NOT EXISTS P360_ADVISOR COMMENT='Read gold only; row policy restricts to their region';
CREATE ROLE IF NOT EXISTS P360_SUPPORT_REVIEWER COMMENT='Support reviewers: read Gold interaction/claim data and Governance tables, use APP_WH';
CREATE ROLE IF NOT EXISTS P360_GOVERNANCE COMMENT='Governance/compliance officers: read Governance schema, read Gold aggregates, audit pipeline runs';

-- Hierarchy: all roles roll up to P360_ADMIN
GRANT ROLE P360_ENGINEER TO ROLE P360_ADMIN;
GRANT ROLE P360_ML_ENGINEER TO ROLE P360_ADMIN;
GRANT ROLE P360_APP_USER TO ROLE P360_ADMIN;
GRANT ROLE P360_ADVISOR TO ROLE P360_ADMIN;
GRANT ROLE P360_SUPPORT_REVIEWER TO ROLE P360_ADMIN;
GRANT ROLE P360_GOVERNANCE TO ROLE P360_ADMIN;
GRANT ROLE P360_ADMIN TO ROLE ACCOUNTADMIN;

-- P360_ENGINEER grants
GRANT USAGE ON DATABASE PROTECT360_DB TO ROLE P360_ENGINEER;
GRANT USAGE ON SCHEMA PROTECT360_DB.BRONZE TO ROLE P360_ENGINEER;
GRANT USAGE ON SCHEMA PROTECT360_DB.SILVER TO ROLE P360_ENGINEER;
GRANT USAGE ON SCHEMA PROTECT360_DB.GOLD TO ROLE P360_ENGINEER;
GRANT USAGE ON SCHEMA PROTECT360_DB.ML TO ROLE P360_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA PROTECT360_DB.BRONZE TO ROLE P360_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA PROTECT360_DB.SILVER TO ROLE P360_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE ON SCHEMA PROTECT360_DB.GOLD TO ROLE P360_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PROTECT360_DB.ML TO ROLE P360_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PROTECT360_DB.BRONZE TO ROLE P360_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PROTECT360_DB.SILVER TO ROLE P360_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PROTECT360_DB.ML TO ROLE P360_ENGINEER;
GRANT USAGE ON WAREHOUSE INGEST_WH TO ROLE P360_ENGINEER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE P360_ENGINEER;
GRANT USAGE ON WAREHOUSE ML_WH TO ROLE P360_ENGINEER;
GRANT USAGE ON WAREHOUSE CORTEX_WH TO ROLE P360_ENGINEER;

-- P360_ML_ENGINEER grants
GRANT USAGE ON DATABASE PROTECT360_DB TO ROLE P360_ML_ENGINEER;
GRANT USAGE ON SCHEMA PROTECT360_DB.SILVER TO ROLE P360_ML_ENGINEER;
GRANT USAGE ON SCHEMA PROTECT360_DB.GOLD TO ROLE P360_ML_ENGINEER;
GRANT USAGE ON SCHEMA PROTECT360_DB.ML TO ROLE P360_ML_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA PROTECT360_DB.SILVER TO ROLE P360_ML_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROTECT360_DB.SILVER TO ROLE P360_ML_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_ML_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_ML_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_ML_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PROTECT360_DB.ML TO ROLE P360_ML_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA PROTECT360_DB.ML TO ROLE P360_ML_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA PROTECT360_DB.ML TO ROLE P360_ML_ENGINEER;
GRANT USAGE ON WAREHOUSE ML_WH TO ROLE P360_ML_ENGINEER;
GRANT USAGE ON WAREHOUSE CORTEX_WH TO ROLE P360_ML_ENGINEER;

-- P360_APP_USER grants
GRANT USAGE ON DATABASE PROTECT360_DB TO ROLE P360_APP_USER;
GRANT USAGE ON SCHEMA PROTECT360_DB.GOLD TO ROLE P360_APP_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_APP_USER;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_APP_USER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_APP_USER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_APP_USER;
GRANT USAGE ON WAREHOUSE APP_WH TO ROLE P360_APP_USER;

-- P360_ADVISOR grants
GRANT USAGE ON DATABASE PROTECT360_DB TO ROLE P360_ADVISOR;
GRANT USAGE ON SCHEMA PROTECT360_DB.GOLD TO ROLE P360_ADVISOR;
GRANT SELECT ON ALL TABLES IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_ADVISOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_ADVISOR;
GRANT USAGE ON WAREHOUSE APP_WH TO ROLE P360_ADVISOR;
GRANT USAGE ON WAREHOUSE CORTEX_WH TO ROLE P360_ADVISOR;

-- P360_SUPPORT_REVIEWER grants
GRANT USAGE ON DATABASE PROTECT360_DB TO ROLE P360_SUPPORT_REVIEWER;
GRANT USAGE ON SCHEMA PROTECT360_DB.GOLD TO ROLE P360_SUPPORT_REVIEWER;
GRANT USAGE ON SCHEMA PROTECT360_DB.GOVERNANCE TO ROLE P360_SUPPORT_REVIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_SUPPORT_REVIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_SUPPORT_REVIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA PROTECT360_DB.GOVERNANCE TO ROLE P360_SUPPORT_REVIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_SUPPORT_REVIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROTECT360_DB.GOVERNANCE TO ROLE P360_SUPPORT_REVIEWER;
GRANT USAGE ON WAREHOUSE APP_WH TO ROLE P360_SUPPORT_REVIEWER;

-- P360_GOVERNANCE grants
GRANT USAGE ON DATABASE PROTECT360_DB TO ROLE P360_GOVERNANCE;
GRANT USAGE ON SCHEMA PROTECT360_DB.GOVERNANCE TO ROLE P360_GOVERNANCE;
GRANT USAGE ON SCHEMA PROTECT360_DB.GOLD TO ROLE P360_GOVERNANCE;
GRANT SELECT ON ALL TABLES IN SCHEMA PROTECT360_DB.GOVERNANCE TO ROLE P360_GOVERNANCE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROTECT360_DB.GOVERNANCE TO ROLE P360_GOVERNANCE;
GRANT SELECT ON ALL TABLES IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_GOVERNANCE;
GRANT SELECT ON ALL VIEWS IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_GOVERNANCE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROTECT360_DB.GOLD TO ROLE P360_GOVERNANCE;
GRANT USAGE ON WAREHOUSE APP_WH TO ROLE P360_GOVERNANCE;
