-- ============================================================
-- BRONZE schema — Raw ingestion layer
-- ============================================================

CREATE TABLE IF NOT EXISTS PROTECT360_DB.BRONZE.AADHAAR_RAW (
    RAW_PAYLOAD VARIANT,
    SOURCE_SYSTEM_CODE VARCHAR DEFAULT 'AADHAAR_SYNTHETIC',
    SOURCE_RECORD_ID VARCHAR,
    INGESTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID VARCHAR,
    RECORD_HASH VARCHAR
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.BRONZE.CLAIM_RAW (
    RAW_PAYLOAD VARIANT,
    SOURCE_SYSTEM_CODE VARCHAR,
    SOURCE_RECORD_ID VARCHAR,
    INGESTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID VARCHAR,
    RECORD_HASH VARCHAR,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.BRONZE.CUSTOMER_RAW (
    RAW_PAYLOAD VARIANT,
    SOURCE_SYSTEM_CODE VARCHAR,
    SOURCE_RECORD_ID VARCHAR,
    INGESTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID VARCHAR,
    RECORD_HASH VARCHAR,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.BRONZE.FINANCIAL_PROFILE_RAW (
    RAW_PAYLOAD VARIANT,
    SOURCE_SYSTEM_CODE VARCHAR,
    SOURCE_RECORD_ID VARCHAR,
    INGESTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID VARCHAR,
    RECORD_HASH VARCHAR,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.BRONZE.HOSPITALIZATION_RAW (
    RAW_PAYLOAD VARIANT,
    SOURCE_SYSTEM_CODE VARCHAR,
    SOURCE_RECORD_ID VARCHAR,
    INGESTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID VARCHAR,
    RECORD_HASH VARCHAR,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.BRONZE.PAN_ITR_RAW (
    RAW_PAYLOAD VARIANT,
    SOURCE_SYSTEM_CODE VARCHAR DEFAULT 'PAN_ITR_SYNTHETIC',
    SOURCE_RECORD_ID VARCHAR,
    INGESTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID VARCHAR,
    RECORD_HASH VARCHAR
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.BRONZE.POLICY_RAW (
    RAW_PAYLOAD VARIANT,
    SOURCE_SYSTEM_CODE VARCHAR,
    SOURCE_RECORD_ID VARCHAR,
    INGESTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID VARCHAR,
    RECORD_HASH VARCHAR,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.BRONZE.POSTCODE_ENRICHMENT_RAW (
    RAW_PAYLOAD VARIANT,
    SOURCE_SYSTEM_CODE VARCHAR,
    SOURCE_RECORD_ID VARCHAR,
    INGESTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID VARCHAR,
    RECORD_HASH VARCHAR,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.BRONZE.SURVEY_RESPONSE_RAW (
    RAW_PAYLOAD VARIANT,
    SOURCE_SYSTEM_CODE VARCHAR DEFAULT 'SURVEY_FORM',
    SOURCE_RECORD_ID VARCHAR,
    INGESTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID VARCHAR,
    RECORD_HASH VARCHAR
);
