-- ============================================================
-- SILVER schema — Conformed and cleansed layer (Dynamic Tables)
-- ============================================================

CREATE OR REPLACE DYNAMIC TABLE PROTECT360_DB.SILVER.CUSTOMER(
    CUSTOMER_SK, CUSTOMER_ID, FULL_NAME, AGE, AGE_BAND, DATE_OF_BIRTH,
    GENDER, STATE_CODE, POSTCODE, SEGMENT_TYPE, STATUS,
    MARKETING_CONSENT_FLAG, HEALTH_DATA_CONSENT_FLAG,
    CUSTOMER_SINCE_DATE, CURRENT_RECORD_FLAG, SOURCE_SYSTEM_CODE,
    INGESTION_TS, SILVER_UPDATED_AT, CREATED_TS
)
TARGET_LAG = '1 hour'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = TRANSFORM_WH
AS
SELECT
    MD5(RAW_PAYLOAD:customer_id::STRING) AS CUSTOMER_SK,
    RAW_PAYLOAD:customer_id::STRING AS CUSTOMER_ID,
    RAW_PAYLOAD:full_name::STRING AS FULL_NAME,
    RAW_PAYLOAD:age::NUMBER AS AGE,
    CASE
        WHEN RAW_PAYLOAD:age::NUMBER < 30 THEN 'Under 30'
        WHEN RAW_PAYLOAD:age::NUMBER BETWEEN 30 AND 44 THEN '30-44'
        WHEN RAW_PAYLOAD:age::NUMBER BETWEEN 45 AND 54 THEN '45-54'
        WHEN RAW_PAYLOAD:age::NUMBER BETWEEN 55 AND 59 THEN '55-59'
        WHEN RAW_PAYLOAD:age::NUMBER BETWEEN 60 AND 64 THEN '60-64'
        WHEN RAW_PAYLOAD:age::NUMBER BETWEEN 65 AND 69 THEN '65-69'
        WHEN RAW_PAYLOAD:age::NUMBER BETWEEN 70 AND 74 THEN '70-74'
        WHEN RAW_PAYLOAD:age::NUMBER BETWEEN 75 AND 79 THEN '75-79'
        WHEN RAW_PAYLOAD:age::NUMBER >= 80 THEN '80+'
        ELSE 'Unknown'
    END AS AGE_BAND,
    RAW_PAYLOAD:date_of_birth::DATE AS DATE_OF_BIRTH,
    RAW_PAYLOAD:gender::STRING AS GENDER,
    RAW_PAYLOAD:state_code::STRING AS STATE_CODE,
    RAW_PAYLOAD:postcode::STRING AS POSTCODE,
    COALESCE(RAW_PAYLOAD:segment_type::STRING, 'SENIOR_CITIZEN') AS SEGMENT_TYPE,
    RAW_PAYLOAD:status::STRING AS STATUS,
    RAW_PAYLOAD:marketing_consent_flag::BOOLEAN AS MARKETING_CONSENT_FLAG,
    RAW_PAYLOAD:health_data_consent_flag::BOOLEAN AS HEALTH_DATA_CONSENT_FLAG,
    RAW_PAYLOAD:customer_since_date::DATE AS CUSTOMER_SINCE_DATE,
    TRUE AS CURRENT_RECORD_FLAG,
    SOURCE_SYSTEM_CODE,
    INGESTION_TS,
    CURRENT_TIMESTAMP() AS SILVER_UPDATED_AT,
    CURRENT_TIMESTAMP() AS CREATED_TS
FROM PROTECT360_DB.BRONZE.CUSTOMER_RAW
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RAW_PAYLOAD:customer_id::STRING
    ORDER BY INGESTION_TS DESC
) = 1;


CREATE OR REPLACE DYNAMIC TABLE PROTECT360_DB.SILVER.CUSTOMER_FINANCIAL_PROFILE(
    FINANCIAL_SK, CUSTOMER_ID, INCOME_BAND, ASSET_BAND,
    ITR_FILING_FLAG, PENSION_INCOME_FLAG, TDS_INDICATOR,
    PMJAY_INCOME_ELIGIBLE, EMPLOYMENT_TYPE_CODE, INCOME_FREQUENCY,
    CAPACITY_SCORE, DATA_AVAILABLE_FLAG, CURRENT_RECORD_FLAG,
    INGESTION_TS, SILVER_UPDATED_AT
)
TARGET_LAG = '1 hour'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = TRANSFORM_WH
AS
SELECT
    MD5(RAW_PAYLOAD:customer_id::STRING) AS FINANCIAL_SK,
    RAW_PAYLOAD:customer_id::STRING AS CUSTOMER_ID,
    RAW_PAYLOAD:income_band::STRING AS INCOME_BAND,
    RAW_PAYLOAD:asset_band::STRING AS ASSET_BAND,
    COALESCE(RAW_PAYLOAD:itr_filing_flag::BOOLEAN, FALSE) AS ITR_FILING_FLAG,
    COALESCE(RAW_PAYLOAD:pension_income_flag::BOOLEAN, FALSE) AS PENSION_INCOME_FLAG,
    COALESCE(RAW_PAYLOAD:tds_indicator::BOOLEAN, FALSE) AS TDS_INDICATOR,
    (RAW_PAYLOAD:income_band::STRING IN ('BELOW_1L', '1L_3L'))::BOOLEAN AS PMJAY_INCOME_ELIGIBLE,
    RAW_PAYLOAD:employment_type_code::STRING AS EMPLOYMENT_TYPE_CODE,
    RAW_PAYLOAD:income_frequency::STRING AS INCOME_FREQUENCY,
    (
        CASE RAW_PAYLOAD:income_band::STRING
            WHEN 'BELOW_1L' THEN 1 WHEN '1L_3L' THEN 2
            WHEN '3L_5L' THEN 4 WHEN '5L_10L' THEN 6
            WHEN 'ABOVE_10L' THEN 9 ELSE 3
        END
        + CASE RAW_PAYLOAD:asset_band::STRING
            WHEN 'BELOW_1L' THEN 0 WHEN '1L_5L' THEN 1
            WHEN '5L_20L' THEN 1 WHEN 'ABOVE_20L' THEN 2 ELSE 1
        END
    )::NUMBER(3,1) AS CAPACITY_SCORE,
    (RAW_PAYLOAD:data_available::BOOLEAN) AS DATA_AVAILABLE_FLAG,
    TRUE AS CURRENT_RECORD_FLAG,
    INGESTION_TS,
    CURRENT_TIMESTAMP() AS SILVER_UPDATED_AT
FROM PROTECT360_DB.BRONZE.FINANCIAL_PROFILE_RAW
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RAW_PAYLOAD:customer_id::STRING
    ORDER BY INGESTION_TS DESC
) = 1;


CREATE OR REPLACE DYNAMIC TABLE PROTECT360_DB.SILVER.CLAIM(
    CLAIM_SK, CLAIM_ID, CUSTOMER_ID, CLAIM_DATE, CLAIM_TYPE,
    DIAGNOSIS_CODE, CLAIM_AMOUNT, CLAIM_STATUS,
    HIGH_SEVERITY_FLAG, HOSPITALIZATION_FLAG, CHRONIC_CONDITION_FLAG,
    CLAIM_IN_LAST_1Y, CLAIM_IN_LAST_3Y, INGESTION_TS, SILVER_UPDATED_AT
)
TARGET_LAG = '1 hour'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = TRANSFORM_WH
AS
SELECT
    MD5(RAW_PAYLOAD:claim_id::STRING) AS CLAIM_SK,
    RAW_PAYLOAD:claim_id::STRING AS CLAIM_ID,
    RAW_PAYLOAD:customer_id::STRING AS CUSTOMER_ID,
    RAW_PAYLOAD:claim_date::DATE AS CLAIM_DATE,
    RAW_PAYLOAD:claim_type::STRING AS CLAIM_TYPE,
    RAW_PAYLOAD:diagnosis_code::STRING AS DIAGNOSIS_CODE,
    RAW_PAYLOAD:claim_amount::NUMBER(12,2) AS CLAIM_AMOUNT,
    RAW_PAYLOAD:claim_status::STRING AS CLAIM_STATUS,
    COALESCE(RAW_PAYLOAD:high_severity_flag::BOOLEAN, FALSE) AS HIGH_SEVERITY_FLAG,
    COALESCE(RAW_PAYLOAD:hospitalization_flag::BOOLEAN, FALSE) AS HOSPITALIZATION_FLAG,
    (RAW_PAYLOAD:diagnosis_code::STRING IN ('E11','N18','I10','J44'))::BOOLEAN AS CHRONIC_CONDITION_FLAG,
    (DATEDIFF('day', RAW_PAYLOAD:claim_date::DATE, CURRENT_DATE()) <= 365)::BOOLEAN AS CLAIM_IN_LAST_1Y,
    (DATEDIFF('day', RAW_PAYLOAD:claim_date::DATE, CURRENT_DATE()) <= 365*3)::BOOLEAN AS CLAIM_IN_LAST_3Y,
    INGESTION_TS,
    CURRENT_TIMESTAMP() AS SILVER_UPDATED_AT
FROM PROTECT360_DB.BRONZE.CLAIM_RAW
WHERE RAW_PAYLOAD:claim_status::STRING != 'REJECTED'
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RAW_PAYLOAD:claim_id::STRING
    ORDER BY INGESTION_TS DESC
) = 1;


CREATE OR REPLACE DYNAMIC TABLE PROTECT360_DB.SILVER.CLAIM_SUMMARY(
    CUSTOMER_ID, CLAIM_COUNT_3Y, CLAIM_AMOUNT_3Y,
    HIGH_SEVERITY_CLAIM_FLAG, HOSPITALIZATION_COUNT_3Y, ICU_STAY_FLAG,
    LAST_CLAIM_DATE, LAST_ADMISSION_DATE, CHRONIC_CONDITION_CLAIM_FLAG,
    HAS_READMISSION_FLAG, OOP_BURDEN_INR, LAST_UPDATED
)
TARGET_LAG = '2 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = TRANSFORM_WH
AS
SELECT
    c.CUSTOMER_ID,
    COUNT(c.CLAIM_ID) AS CLAIM_COUNT_3Y,
    SUM(c.CLAIM_AMOUNT) AS CLAIM_AMOUNT_3Y,
    BOOLOR_AGG(c.HIGH_SEVERITY_FLAG) AS HIGH_SEVERITY_CLAIM_FLAG,
    COUNT(h.HOSPITALIZATION_ID) AS HOSPITALIZATION_COUNT_3Y,
    BOOLOR_AGG(h.ICU_STAY_FLAG) AS ICU_STAY_FLAG,
    MAX(c.CLAIM_DATE) AS LAST_CLAIM_DATE,
    MAX(h.ADMISSION_DATE) AS LAST_ADMISSION_DATE,
    BOOLOR_AGG(c.CHRONIC_CONDITION_FLAG) AS CHRONIC_CONDITION_CLAIM_FLAG,
    BOOLOR_AGG(h.READMISSION_30D_FLAG) AS HAS_READMISSION_FLAG,
    COALESCE(SUM(h.TOTAL_BILLED_INR - h.INSURANCE_COVERED_INR), 0) AS OOP_BURDEN_INR,
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM PROTECT360_DB.SILVER.CLAIM c
LEFT JOIN PROTECT360_DB.SILVER.HOSPITALIZATION h
    ON c.CUSTOMER_ID = h.CUSTOMER_ID AND h.IN_LAST_3Y = TRUE
WHERE c.CLAIM_IN_LAST_3Y = TRUE
GROUP BY c.CUSTOMER_ID;


CREATE OR REPLACE DYNAMIC TABLE PROTECT360_DB.SILVER.HOSPITALIZATION(
    HOSPITALIZATION_SK, HOSPITALIZATION_ID, CUSTOMER_ID,
    ADMISSION_DATE, DISCHARGE_DATE, LOS_DAYS, TREATMENT_CATEGORY,
    PRIMARY_DIAGNOSIS, ICU_STAY_FLAG, TOTAL_BILLED_INR,
    INSURANCE_COVERED_INR, READMISSION_30D_FLAG, IN_LAST_3Y,
    INGESTION_TS, SILVER_UPDATED_AT
)
TARGET_LAG = '1 hour'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = TRANSFORM_WH
AS
SELECT
    MD5(RAW_PAYLOAD:hospitalization_id::STRING) AS HOSPITALIZATION_SK,
    RAW_PAYLOAD:hospitalization_id::STRING AS HOSPITALIZATION_ID,
    RAW_PAYLOAD:customer_id::STRING AS CUSTOMER_ID,
    RAW_PAYLOAD:admission_date::DATE AS ADMISSION_DATE,
    RAW_PAYLOAD:discharge_date::DATE AS DISCHARGE_DATE,
    RAW_PAYLOAD:los_days::INTEGER AS LOS_DAYS,
    RAW_PAYLOAD:treatment_category::STRING AS TREATMENT_CATEGORY,
    RAW_PAYLOAD:primary_diagnosis::STRING AS PRIMARY_DIAGNOSIS,
    COALESCE(RAW_PAYLOAD:icu_stay_flag::BOOLEAN, FALSE) AS ICU_STAY_FLAG,
    RAW_PAYLOAD:total_billed_inr::NUMBER(12,2) AS TOTAL_BILLED_INR,
    RAW_PAYLOAD:insurance_covered_inr::NUMBER(12,2) AS INSURANCE_COVERED_INR,
    COALESCE(RAW_PAYLOAD:readmission_30d_flag::BOOLEAN, FALSE) AS READMISSION_30D_FLAG,
    (DATEDIFF('day', RAW_PAYLOAD:admission_date::DATE, CURRENT_DATE()) <= 365*3)::BOOLEAN AS IN_LAST_3Y,
    INGESTION_TS,
    CURRENT_TIMESTAMP() AS SILVER_UPDATED_AT
FROM PROTECT360_DB.BRONZE.HOSPITALIZATION_RAW
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RAW_PAYLOAD:hospitalization_id::STRING
    ORDER BY INGESTION_TS DESC
) = 1;


CREATE OR REPLACE DYNAMIC TABLE PROTECT360_DB.SILVER.AADHAAR_PROFILE(
    AADHAAR_SK, CUSTOMER_ID, AADHAAR_ID, AADHAAR_VERIFIED_FLAG,
    KYC_DATE, INGESTION_TS, SILVER_UPDATED_AT
)
TARGET_LAG = '1 hour'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = TRANSFORM_WH
AS
SELECT
    MD5(RAW_PAYLOAD:customer_id::STRING) AS AADHAAR_SK,
    RAW_PAYLOAD:customer_id::STRING AS CUSTOMER_ID,
    RAW_PAYLOAD:aadhaar_id::STRING AS AADHAAR_ID,
    COALESCE(RAW_PAYLOAD:verified_flag::BOOLEAN, FALSE) AS AADHAAR_VERIFIED_FLAG,
    RAW_PAYLOAD:kyc_date::DATE AS KYC_DATE,
    INGESTION_TS,
    CURRENT_TIMESTAMP() AS SILVER_UPDATED_AT
FROM PROTECT360_DB.BRONZE.AADHAAR_RAW
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RAW_PAYLOAD:customer_id::STRING
    ORDER BY INGESTION_TS DESC
) = 1;


CREATE OR REPLACE DYNAMIC TABLE PROTECT360_DB.SILVER.PAN_ITR_PROFILE(
    PAN_ITR_SK, CUSTOMER_ID, PAN_NUMBER, PAN_VERIFIED_FLAG,
    ITR_FILED_FY, INGESTION_TS, SILVER_UPDATED_AT
)
TARGET_LAG = '1 hour'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = TRANSFORM_WH
AS
SELECT
    MD5(RAW_PAYLOAD:customer_id::STRING) AS PAN_ITR_SK,
    RAW_PAYLOAD:customer_id::STRING AS CUSTOMER_ID,
    RAW_PAYLOAD:pan_number::STRING AS PAN_NUMBER,
    COALESCE(RAW_PAYLOAD:pan_verified::BOOLEAN, FALSE) AS PAN_VERIFIED_FLAG,
    RAW_PAYLOAD:itr_filed_fy::STRING AS ITR_FILED_FY,
    INGESTION_TS,
    CURRENT_TIMESTAMP() AS SILVER_UPDATED_AT
FROM PROTECT360_DB.BRONZE.PAN_ITR_RAW
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RAW_PAYLOAD:customer_id::STRING
    ORDER BY INGESTION_TS DESC
) = 1;


CREATE OR REPLACE DYNAMIC TABLE PROTECT360_DB.SILVER.POLICY(
    POLICY_SK, POLICY_ID, CUSTOMER_ID, PRODUCT_TYPE, STATUS,
    ANNUAL_PREMIUM, POLICY_START_DATE, POLICY_END_DATE,
    RENEWAL_DATE, LAPSE_DATE, CURRENT_RECORD_FLAG,
    INGESTION_TS, SILVER_UPDATED_AT, CREATED_TS
)
TARGET_LAG = '1 hour'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = TRANSFORM_WH
AS
SELECT
    MD5(RAW_PAYLOAD:policy_id::STRING)            AS POLICY_SK,
    RAW_PAYLOAD:policy_id::STRING                 AS POLICY_ID,
    RAW_PAYLOAD:customer_id::STRING               AS CUSTOMER_ID,
    RAW_PAYLOAD:product_type::STRING              AS PRODUCT_TYPE,
    RAW_PAYLOAD:status::STRING                    AS STATUS,
    RAW_PAYLOAD:annual_premium::NUMBER(12,2)      AS ANNUAL_PREMIUM,
    RAW_PAYLOAD:policy_start_date::DATE           AS POLICY_START_DATE,
    RAW_PAYLOAD:policy_end_date::DATE             AS POLICY_END_DATE,
    RAW_PAYLOAD:renewal_date::DATE                AS RENEWAL_DATE,
    RAW_PAYLOAD:lapse_date::DATE                  AS LAPSE_DATE,
    TRUE                                          AS CURRENT_RECORD_FLAG,
    INGESTION_TS,
    CURRENT_TIMESTAMP()                           AS SILVER_UPDATED_AT,
    CURRENT_TIMESTAMP()                           AS CREATED_TS
FROM PROTECT360_DB.BRONZE.POLICY_RAW
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RAW_PAYLOAD:policy_id::STRING
    ORDER BY INGESTION_TS DESC
) = 1;


CREATE OR REPLACE DYNAMIC TABLE PROTECT360_DB.SILVER.POLICY_SUMMARY(
    CUSTOMER_ID, ACTIVE_POLICY_COUNT, CURRENT_COVERAGE_TYPE,
    TOTAL_ANNUAL_PREMIUM, PROTECTION_GAP_FLAG, HAS_ANY_COVERAGE_FLAG,
    LAST_UPDATED
)
TARGET_LAG = '2 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = TRANSFORM_WH
AS
SELECT
    CUSTOMER_ID,
    COUNT(CASE WHEN STATUS = 'ACTIVE' THEN 1 END) AS ACTIVE_POLICY_COUNT,
    MAX(CASE WHEN STATUS = 'ACTIVE' THEN PRODUCT_TYPE END) AS CURRENT_COVERAGE_TYPE,
    COALESCE(SUM(
        CASE WHEN STATUS = 'ACTIVE' THEN ANNUAL_PREMIUM ELSE 0 END
    ), 0) AS TOTAL_ANNUAL_PREMIUM,
    (COUNT(CASE WHEN STATUS = 'ACTIVE' THEN 1 END) = 0)::BOOLEAN AS PROTECTION_GAP_FLAG,
    BOOLOR_AGG(STATUS = 'ACTIVE') AS HAS_ANY_COVERAGE_FLAG,
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM PROTECT360_DB.SILVER.POLICY
GROUP BY CUSTOMER_ID;


CREATE OR REPLACE DYNAMIC TABLE PROTECT360_DB.SILVER.POSTCODE_ENRICHMENT(
    POSTCODE, CITY_TIER, SOCIOECONOMIC_DECILE, HEALTH_ACCESS_INDEX,
    INCOME_INDEX, EFFECTIVE_DATE, SILVER_UPDATED_AT
)
TARGET_LAG = '1 hour'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = TRANSFORM_WH
AS
SELECT
    RAW_PAYLOAD:postcode::STRING AS POSTCODE,
    RAW_PAYLOAD:city_tier::INTEGER AS CITY_TIER,
    RAW_PAYLOAD:socioeconomic_decile::NUMBER AS SOCIOECONOMIC_DECILE,
    RAW_PAYLOAD:health_access_index::NUMBER(4,2) AS HEALTH_ACCESS_INDEX,
    RAW_PAYLOAD:income_index::NUMBER(4,2) AS INCOME_INDEX,
    RAW_PAYLOAD:effective_date::DATE AS EFFECTIVE_DATE,
    CURRENT_TIMESTAMP() AS SILVER_UPDATED_AT
FROM PROTECT360_DB.BRONZE.POSTCODE_ENRICHMENT_RAW
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RAW_PAYLOAD:postcode::STRING
    ORDER BY INGESTION_TS DESC
) = 1;


CREATE OR REPLACE DYNAMIC TABLE PROTECT360_DB.SILVER.SURVEY_RESPONSE(
    SURVEY_SK, SURVEY_ID, CUSTOMER_ID, SUBMITTED_BY,
    HEALTH_CONDITIONS_RAW, HAS_DIABETES, HAS_HYPERTENSION,
    HAS_HEART_DISEASE, HAS_COPD, HAS_ARTHRITIS, HAS_ANY_CONDITION,
    CONDITION_COUNT, CURRENT_COVERAGE_STATUS, IS_UNINSURED,
    LIVING_SITUATION, LIVING_ALONE_FLAG, IN_CARE_HOME_FLAG,
    PREFERRED_SERVICES_RAW, WANTS_TELEMEDICINE, WANTS_HOME_VISIT,
    WANTS_ELDER_CARE, WANTS_FINANCIAL_ADVICE, WANTS_CHECKUP,
    SURVEY_SUBMITTED_DATE, INGESTION_TS, SILVER_UPDATED_AT
)
TARGET_LAG = '1 hour'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = TRANSFORM_WH
AS
SELECT
    MD5(RAW_PAYLOAD:survey_id::STRING) AS SURVEY_SK,
    RAW_PAYLOAD:survey_id::STRING AS SURVEY_ID,
    RAW_PAYLOAD:customer_id::STRING AS CUSTOMER_ID,
    RAW_PAYLOAD:submitted_by::STRING AS SUBMITTED_BY,
    RAW_PAYLOAD:health_conditions::STRING AS HEALTH_CONDITIONS_RAW,
    CONTAINS(RAW_PAYLOAD:health_conditions::STRING, 'diabetes') AS HAS_DIABETES,
    CONTAINS(RAW_PAYLOAD:health_conditions::STRING, 'hypertension') AS HAS_HYPERTENSION,
    CONTAINS(RAW_PAYLOAD:health_conditions::STRING, 'heart_disease') AS HAS_HEART_DISEASE,
    CONTAINS(RAW_PAYLOAD:health_conditions::STRING, 'copd') AS HAS_COPD,
    CONTAINS(RAW_PAYLOAD:health_conditions::STRING, 'arthritis') AS HAS_ARTHRITIS,
    NOT CONTAINS(RAW_PAYLOAD:health_conditions::STRING, 'none_of_above')
        AND RAW_PAYLOAD:health_conditions::STRING IS NOT NULL AS HAS_ANY_CONDITION,
    (
        IFF(CONTAINS(RAW_PAYLOAD:health_conditions::STRING, 'diabetes'), 1, 0) +
        IFF(CONTAINS(RAW_PAYLOAD:health_conditions::STRING, 'hypertension'), 1, 0) +
        IFF(CONTAINS(RAW_PAYLOAD:health_conditions::STRING, 'heart_disease'), 1, 0) +
        IFF(CONTAINS(RAW_PAYLOAD:health_conditions::STRING, 'copd'), 1, 0) +
        IFF(CONTAINS(RAW_PAYLOAD:health_conditions::STRING, 'arthritis'), 1, 0)
    ) AS CONDITION_COUNT,
    RAW_PAYLOAD:current_coverage::STRING AS CURRENT_COVERAGE_STATUS,
    (RAW_PAYLOAD:current_coverage::STRING = 'none')::BOOLEAN AS IS_UNINSURED,
    RAW_PAYLOAD:living_situation::STRING AS LIVING_SITUATION,
    (RAW_PAYLOAD:living_situation::STRING = 'alone')::BOOLEAN AS LIVING_ALONE_FLAG,
    (RAW_PAYLOAD:living_situation::STRING = 'care_home')::BOOLEAN AS IN_CARE_HOME_FLAG,
    RAW_PAYLOAD:preferred_services::STRING AS PREFERRED_SERVICES_RAW,
    CONTAINS(RAW_PAYLOAD:preferred_services::STRING, 'telemedicine') AS WANTS_TELEMEDICINE,
    CONTAINS(RAW_PAYLOAD:preferred_services::STRING, 'home_visit') AS WANTS_HOME_VISIT,
    CONTAINS(RAW_PAYLOAD:preferred_services::STRING, 'elder_care') AS WANTS_ELDER_CARE,
    CONTAINS(RAW_PAYLOAD:preferred_services::STRING, 'financial_advice') AS WANTS_FINANCIAL_ADVICE,
    CONTAINS(RAW_PAYLOAD:preferred_services::STRING, 'checkup') AS WANTS_CHECKUP,
    RAW_PAYLOAD:submitted_ts::DATE AS SURVEY_SUBMITTED_DATE,
    INGESTION_TS,
    CURRENT_TIMESTAMP() AS SILVER_UPDATED_AT
FROM PROTECT360_DB.BRONZE.SURVEY_RESPONSE_RAW
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RAW_PAYLOAD:customer_id::STRING
    ORDER BY INGESTION_TS DESC
) = 1;


CREATE OR REPLACE DYNAMIC TABLE PROTECT360_DB.SILVER.SURVEY_SUMMARY(
    CUSTOMER_ID, SURVEY_ID, SUBMITTED_BY,
    CONDITION_COUNT, HAS_DIABETES, HAS_HYPERTENSION, HAS_HEART_DISEASE,
    HAS_COPD, HAS_ARTHRITIS, HAS_ANY_CONDITION,
    CURRENT_COVERAGE_STATUS, IS_UNINSURED,
    LIVING_SITUATION, LIVING_ALONE_FLAG, IN_CARE_HOME_FLAG,
    WANTS_TELEMEDICINE, WANTS_HOME_VISIT, WANTS_ELDER_CARE,
    WANTS_FINANCIAL_ADVICE, WANTS_CHECKUP,
    PREFERRED_SERVICES_RAW, HEALTH_CONDITIONS_RAW,
    SURVEY_SUBMITTED_DATE, CARE_NEEDS_FLAG,
    SURVEY_COMPLETENESS_SCORE, LAST_UPDATED
)
TARGET_LAG = '2 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = TRANSFORM_WH
AS
SELECT
    CUSTOMER_ID, SURVEY_ID, SUBMITTED_BY,
    CONDITION_COUNT, HAS_DIABETES, HAS_HYPERTENSION, HAS_HEART_DISEASE,
    HAS_COPD, HAS_ARTHRITIS, HAS_ANY_CONDITION,
    CURRENT_COVERAGE_STATUS, IS_UNINSURED,
    LIVING_SITUATION, LIVING_ALONE_FLAG, IN_CARE_HOME_FLAG,
    WANTS_TELEMEDICINE, WANTS_HOME_VISIT, WANTS_ELDER_CARE,
    WANTS_FINANCIAL_ADVICE, WANTS_CHECKUP,
    PREFERRED_SERVICES_RAW, HEALTH_CONDITIONS_RAW,
    SURVEY_SUBMITTED_DATE,
    (LIVING_ALONE_FLAG AND HAS_ANY_CONDITION) OR IN_CARE_HOME_FLAG AS CARE_NEEDS_FLAG,
    (
        IFF(CURRENT_COVERAGE_STATUS IS NOT NULL, 1, 0) +
        IFF(LIVING_SITUATION IS NOT NULL, 1, 0) +
        IFF(HEALTH_CONDITIONS_RAW IS NOT NULL, 1, 0) +
        IFF(PREFERRED_SERVICES_RAW IS NOT NULL, 1, 0) +
        IFF(SURVEY_SUBMITTED_DATE IS NOT NULL, 1, 0)
    ) / 5.0 AS SURVEY_COMPLETENESS_SCORE,
    CURRENT_TIMESTAMP() AS LAST_UPDATED
FROM PROTECT360_DB.SILVER.SURVEY_RESPONSE;
