-- ============================================================
-- GOLD schema — Customer 360 and Next Best Action layer
-- ============================================================

-- Static tables

CREATE TABLE IF NOT EXISTS PROTECT360_DB.GOLD.ACTION_OUTCOME (
    ACTION_OUTCOME_SK VARCHAR NOT NULL,
    NEXT_BEST_ACTION_SK VARCHAR,
    CUSTOMER_KEY VARCHAR,
    ADVISOR_DECISION VARCHAR,
    ADVISOR_FEEDBACK VARCHAR,
    CUSTOMER_RESPONSE VARCHAR,
    CONVERSION_FLAG BOOLEAN,
    OUTCOME_VALUE NUMBER(12,2),
    OUTCOME_RECORDED_TS TIMESTAMP_NTZ,
    FOLLOW_UP_REQUIRED BOOLEAN,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ACTION_OUTCOME_SK)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.GOLD.CUSTOMER_FEATURE_SNAPSHOT (
    SNAPSHOT_ID VARCHAR NOT NULL,
    CUSTOMER_KEY VARCHAR NOT NULL,
    FEATURE_SNAPSHOT_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FEATURE_SET_VERSION VARCHAR DEFAULT 'v2.0_INDIA',
    AGE NUMBER(38,0),
    AGE_BAND VARCHAR,
    GENDER VARCHAR,
    CITY_TIER NUMBER(38,0),
    STATE_CODE VARCHAR,
    INCOME_BAND VARCHAR,
    ITR_FILING_FLAG BOOLEAN,
    PENSION_INCOME_FLAG BOOLEAN,
    PMJAY_INCOME_ELIGIBLE BOOLEAN,
    CAPACITY_SCORE FLOAT,
    CONDITION_COUNT NUMBER(38,0),
    CURRENT_COVERAGE_STATUS VARCHAR,
    LIVING_ALONE_FLAG BOOLEAN,
    CARE_NEEDS_FLAG BOOLEAN,
    HAS_PREFERRED_SERVICES BOOLEAN,
    CLAIMS_DATA_AVAILABLE BOOLEAN,
    CLAIM_COUNT_3Y NUMBER(38,0),
    HOSPITALIZATION_COUNT_3Y NUMBER(38,0),
    HIGH_SEVERITY_CLAIM_FLAG BOOLEAN,
    CHRONIC_CONDITION_CLAIM_FLAG BOOLEAN,
    OOP_BURDEN_INR NUMBER(12,2),
    VULNERABILITY_SCORE FLOAT,
    PROTECTION_GAP_FLAG BOOLEAN,
    SURVEY_COMPLETENESS_SCORE FLOAT,
    SEGMENT_TYPE VARCHAR,
    EMPLOYMENT_TYPE_CODE VARCHAR,
    INCOME_FREQUENCY VARCHAR,
    DATA_COMPLETENESS_SCORE FLOAT,
    LABEL_CUTOFF_TS TIMESTAMP_NTZ,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.GOLD.NBA_ACTION_CANDIDATE (
    ACTION_CANDIDATE_SK VARCHAR NOT NULL,
    CUSTOMER_KEY VARCHAR,
    ACTION_KEY VARCHAR,
    NBA_RUN_ID VARCHAR,
    ELIGIBLE_FLAG BOOLEAN,
    SUPPRESSION_REASON_CODE VARCHAR,
    CUSTOMER_NEED_SCORE NUMBER(5,4),
    PROPENSITY_SCORE NUMBER(5,4),
    URGENCY_SCORE NUMBER(5,4),
    SERVICE_VALUE_SCORE NUMBER(5,4),
    BUSINESS_PRIORITY_SCORE NUMBER(5,4),
    CONTACT_FATIGUE_PENALTY NUMBER(5,4),
    FINAL_ACTION_SCORE NUMBER(5,4) COMMENT '0.35*NEED+0.25*PROPENSITY+0.20*URGENCY+0.10*SERVICE+0.10*PRIORITY-FATIGUE',
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ACTION_CANDIDATE_SK)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.GOLD.NBA_ACTION_CATALOG (
    ACTION_KEY VARCHAR NOT NULL,
    ACTION_ID VARCHAR,
    ACTION_NAME VARCHAR,
    ACTION_CATEGORY VARCHAR,
    DESCRIPTION VARCHAR,
    DEFAULT_CHANNEL VARCHAR,
    COOL_OFF_DAYS NUMBER(38,0),
    REQUIRES_HUMAN_REVIEW BOOLEAN,
    ACTIVE_FROM_DATE DATE,
    ACTIVE_TO_DATE DATE,
    ACTIVE_FLAG BOOLEAN DEFAULT TRUE,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ACTION_KEY)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.GOLD.NBA_ACTION_RULE (
    ACTION_RULE_SK VARCHAR NOT NULL,
    ACTION_KEY VARCHAR,
    RULE_TYPE VARCHAR,
    RULE_EXPRESSION VARCHAR,
    RULE_DESCRIPTION VARCHAR,
    PRIORITY NUMBER(38,0),
    RULE_VERSION VARCHAR,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ACTION_RULE_SK)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.GOLD.NEXT_BEST_ACTION (
    NEXT_BEST_ACTION_SK VARCHAR NOT NULL,
    CUSTOMER_KEY VARCHAR,
    ACTION_KEY VARCHAR,
    NBA_RUN_ID VARCHAR,
    PRIORITY_RANK NUMBER(38,0),
    FINAL_ACTION_SCORE NUMBER(5,4),
    RECOMMENDED_CHANNEL VARCHAR,
    REASON_TEXT VARCHAR,
    ADVISOR_MESSAGE VARCHAR,
    ACTION_EXPIRY_TS TIMESTAMP_NTZ,
    HUMAN_REVIEW_REQUIRED BOOLEAN,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (NEXT_BEST_ACTION_SK)
);


-- Dynamic table: Customer 360 Profile

CREATE OR REPLACE DYNAMIC TABLE PROTECT360_DB.GOLD.CUSTOMER_360_PROFILE(
    CUSTOMER_KEY, CUSTOMER_ID, AGE, AGE_BAND, GENDER, STATE_CODE, POSTCODE,
    SEGMENT_TYPE, MARKETING_CONSENT_FLAG, HEALTH_DATA_CONSENT_FLAG,
    AADHAAR_VERIFIED_FLAG, PAN_VERIFIED_FLAG, CITY_TIER, SOCIOECONOMIC_DECILE,
    HEALTH_ACCESS_INDEX, INCOME_BAND, ASSET_BAND, CAPACITY_SCORE,
    ITR_FILING_FLAG, PENSION_INCOME_FLAG, TDS_INDICATOR, PMJAY_INCOME_ELIGIBLE,
    EMPLOYMENT_TYPE_CODE, INCOME_FREQUENCY, FINANCIAL_DATA_AVAILABLE,
    ACTIVE_POLICY_COUNT, PROTECTION_GAP_FLAG, HAS_ANY_COVERAGE_FLAG,
    CURRENT_COVERAGE_TYPE, TOTAL_ANNUAL_PREMIUM, CONDITION_COUNT,
    HAS_DIABETES, HAS_HYPERTENSION, HAS_HEART_DISEASE, HAS_ANY_CONDITION,
    CURRENT_COVERAGE_STATUS, IS_UNINSURED, LIVING_SITUATION, LIVING_ALONE_FLAG,
    CARE_NEEDS_FLAG, WANTS_TELEMEDICINE, WANTS_HOME_VISIT, WANTS_ELDER_CARE,
    WANTS_FINANCIAL_ADVICE, WANTS_CHECKUP, PREFERRED_SERVICES_RAW,
    SURVEY_SUBMITTED_DATE, SURVEY_COMPLETENESS_SCORE, SURVEY_COMPLETED_FLAG,
    CLAIMS_DATA_AVAILABLE, CLAIM_COUNT_3Y, CLAIM_AMOUNT_3Y,
    HIGH_SEVERITY_CLAIM_FLAG, HOSPITALIZATION_COUNT_3Y, ICU_STAY_FLAG,
    LAST_CLAIM_DATE, LAST_ADMISSION_DATE, CHRONIC_CONDITION_CLAIM_FLAG,
    HAS_READMISSION_FLAG, OOP_BURDEN_INR, SENIOR_FLAG, ELDERLY_FLAG,
    GIG_WORKER_FLAG, VULNERABILITY_SCORE, GOVT_SCHEME_ELIGIBLE_FLAG,
    COMPLETENESS_SCORE, HIGH_URGENCY_FLAG, DQ_STATUS, PROFILE_AS_OF_TS
)
TARGET_LAG = '2 hours'
REFRESH_MODE = AUTO
INITIALIZE = ON_CREATE
WAREHOUSE = TRANSFORM_WH
AS
WITH base AS (
    SELECT
        MD5(CAST(c.CUSTOMER_ID AS VARCHAR)) AS CUSTOMER_KEY,
        c.CUSTOMER_ID, c.AGE, c.AGE_BAND, c.GENDER, c.STATE_CODE, c.POSTCODE,
        c.SEGMENT_TYPE, c.MARKETING_CONSENT_FLAG, c.HEALTH_DATA_CONSENT_FLAG,
        COALESCE(adh.AADHAAR_VERIFIED_FLAG, FALSE) AS AADHAAR_VERIFIED_FLAG,
        COALESCE(pan.PAN_VERIFIED_FLAG, FALSE) AS PAN_VERIFIED_FLAG,
        COALESCE(pe.CITY_TIER, 3) AS CITY_TIER,
        pe.SOCIOECONOMIC_DECILE, pe.HEALTH_ACCESS_INDEX,
        CASE WHEN cfp.DATA_AVAILABLE_FLAG THEN cfp.INCOME_BAND END AS INCOME_BAND,
        CASE WHEN cfp.DATA_AVAILABLE_FLAG THEN cfp.ASSET_BAND END AS ASSET_BAND,
        CASE WHEN cfp.DATA_AVAILABLE_FLAG THEN cfp.CAPACITY_SCORE END AS CAPACITY_SCORE,
        CASE WHEN cfp.DATA_AVAILABLE_FLAG THEN cfp.ITR_FILING_FLAG END AS ITR_FILING_FLAG,
        CASE WHEN cfp.DATA_AVAILABLE_FLAG THEN cfp.PENSION_INCOME_FLAG END AS PENSION_INCOME_FLAG,
        CASE WHEN cfp.DATA_AVAILABLE_FLAG THEN cfp.TDS_INDICATOR END AS TDS_INDICATOR,
        CASE WHEN cfp.DATA_AVAILABLE_FLAG THEN cfp.PMJAY_INCOME_ELIGIBLE END AS PMJAY_INCOME_ELIGIBLE,
        CASE WHEN cfp.DATA_AVAILABLE_FLAG THEN cfp.EMPLOYMENT_TYPE_CODE END AS EMPLOYMENT_TYPE_CODE,
        CASE WHEN cfp.DATA_AVAILABLE_FLAG THEN cfp.INCOME_FREQUENCY END AS INCOME_FREQUENCY,
        cfp.DATA_AVAILABLE_FLAG AS FINANCIAL_DATA_AVAILABLE,
        COALESCE(ps.ACTIVE_POLICY_COUNT, 0) AS ACTIVE_POLICY_COUNT,
        COALESCE(ps.PROTECTION_GAP_FLAG, TRUE) AS PROTECTION_GAP_FLAG,
        COALESCE(ps.HAS_ANY_COVERAGE_FLAG, FALSE) AS HAS_ANY_COVERAGE_FLAG,
        ps.CURRENT_COVERAGE_TYPE,
        COALESCE(ps.TOTAL_ANNUAL_PREMIUM, 0) AS TOTAL_ANNUAL_PREMIUM,
        srv.CONDITION_COUNT, srv.HAS_DIABETES, srv.HAS_HYPERTENSION, srv.HAS_HEART_DISEASE,
        srv.HAS_ANY_CONDITION, srv.CURRENT_COVERAGE_STATUS,
        COALESCE(srv.IS_UNINSURED, TRUE) AS IS_UNINSURED,
        srv.LIVING_SITUATION,
        COALESCE(srv.LIVING_ALONE_FLAG, FALSE) AS LIVING_ALONE_FLAG,
        COALESCE(srv.CARE_NEEDS_FLAG, FALSE) AS CARE_NEEDS_FLAG,
        srv.WANTS_TELEMEDICINE, srv.WANTS_HOME_VISIT, srv.WANTS_ELDER_CARE,
        srv.WANTS_FINANCIAL_ADVICE, srv.WANTS_CHECKUP,
        srv.PREFERRED_SERVICES_RAW, srv.SURVEY_SUBMITTED_DATE,
        COALESCE(srv.SURVEY_COMPLETENESS_SCORE, 0.0) AS SURVEY_COMPLETENESS_SCORE,
        (srv.SURVEY_ID IS NOT NULL)::BOOLEAN AS SURVEY_COMPLETED_FLAG,
        (cs.CUSTOMER_ID IS NOT NULL)::BOOLEAN AS CLAIMS_DATA_AVAILABLE,
        cs.CLAIM_COUNT_3Y, cs.CLAIM_AMOUNT_3Y, cs.HIGH_SEVERITY_CLAIM_FLAG,
        cs.HOSPITALIZATION_COUNT_3Y, cs.ICU_STAY_FLAG, cs.LAST_CLAIM_DATE,
        cs.LAST_ADMISSION_DATE, cs.CHRONIC_CONDITION_CLAIM_FLAG,
        cs.HAS_READMISSION_FLAG, cs.OOP_BURDEN_INR
    FROM PROTECT360_DB.SILVER.CUSTOMER c
    LEFT JOIN PROTECT360_DB.SILVER.AADHAAR_PROFILE adh ON c.CUSTOMER_ID = adh.CUSTOMER_ID
    LEFT JOIN PROTECT360_DB.SILVER.PAN_ITR_PROFILE pan ON c.CUSTOMER_ID = pan.CUSTOMER_ID
    LEFT JOIN PROTECT360_DB.SILVER.CUSTOMER_FINANCIAL_PROFILE cfp
        ON c.CUSTOMER_ID = cfp.CUSTOMER_ID AND cfp.CURRENT_RECORD_FLAG = TRUE
    LEFT JOIN PROTECT360_DB.SILVER.POLICY_SUMMARY ps ON c.CUSTOMER_ID = ps.CUSTOMER_ID
    LEFT JOIN PROTECT360_DB.SILVER.SURVEY_SUMMARY srv ON c.CUSTOMER_ID = srv.CUSTOMER_ID
    LEFT JOIN PROTECT360_DB.SILVER.POSTCODE_ENRICHMENT pe ON c.POSTCODE = pe.POSTCODE
    LEFT JOIN PROTECT360_DB.SILVER.CLAIM_SUMMARY cs ON c.CUSTOMER_ID = cs.CUSTOMER_ID
    WHERE c.CURRENT_RECORD_FLAG = TRUE
),
scored AS (
    SELECT b.*,
        (b.AGE BETWEEN 60 AND 69)::BOOLEAN AS SENIOR_FLAG,
        (b.AGE >= 70)::BOOLEAN AS ELDERLY_FLAG,
        (b.AGE < 60 AND b.SEGMENT_TYPE = 'GIG_WORKER')::BOOLEAN AS GIG_WORKER_FLAG,
        LEAST(1.0,
            CASE WHEN b.AGE >= 80 THEN 0.40 WHEN b.AGE >= 75 THEN 0.35
                 WHEN b.AGE >= 70 THEN 0.30 WHEN b.AGE >= 65 THEN 0.25
                 WHEN b.AGE >= 60 THEN 0.20 ELSE 0.10 END
            + IFF(COALESCE(b.PROTECTION_GAP_FLAG, TRUE), 0.25, 0.0)
            + LEAST(0.20, COALESCE(b.CONDITION_COUNT, 0) * 0.07)
            + IFF(COALESCE(b.LIVING_ALONE_FLAG, FALSE), 0.10, 0.0)
            + IFF(COALESCE(b.CARE_NEEDS_FLAG, FALSE), 0.05, 0.0)
            + IFF(COALESCE(b.CLAIMS_DATA_AVAILABLE, FALSE),
                LEAST(0.15,
                    LEAST(0.09, COALESCE(b.HOSPITALIZATION_COUNT_3Y, 0) * 0.03)
                    + IFF(COALESCE(b.HIGH_SEVERITY_CLAIM_FLAG, FALSE), 0.08, 0.0)
                    + IFF(COALESCE(b.CHRONIC_CONDITION_CLAIM_FLAG, FALSE), 0.05, 0.0)
                    + IFF(COALESCE(b.HAS_READMISSION_FLAG, FALSE), 0.04, 0.0)
                ), 0.0)
        ) AS VULNERABILITY_SCORE,
        COALESCE(b.PMJAY_INCOME_ELIGIBLE, FALSE) AND COALESCE(b.IS_UNINSURED, TRUE)
            AS GOVT_SCHEME_ELIGIBLE_FLAG,
        (
            IFF(b.INCOME_BAND IS NOT NULL, 1, 0) + IFF(b.CONDITION_COUNT IS NOT NULL, 1, 0) +
            IFF(b.CURRENT_COVERAGE_STATUS IS NOT NULL, 1, 0) + IFF(b.LIVING_SITUATION IS NOT NULL, 1, 0) +
            IFF(b.CITY_TIER IS NOT NULL, 1, 0) + IFF(b.AADHAAR_VERIFIED_FLAG = TRUE, 1, 0) +
            IFF(b.SURVEY_COMPLETED_FLAG = TRUE, 1, 0) + IFF(b.SOCIOECONOMIC_DECILE IS NOT NULL, 1, 0)
        ) / 8.0 AS COMPLETENESS_SCORE
    FROM base b
)
SELECT s.*,
    (s.AGE >= 70 AND s.IS_UNINSURED)::BOOLEAN AS HIGH_URGENCY_FLAG,
    CASE WHEN s.COMPLETENESS_SCORE >= 0.7 THEN 'GREEN'
         WHEN s.COMPLETENESS_SCORE >= 0.4 THEN 'AMBER'
         ELSE 'RED' END AS DQ_STATUS,
    CURRENT_TIMESTAMP() AS PROFILE_AS_OF_TS
FROM scored s;
