-- ============================================================
-- GOLD schema — Secure Views
-- ============================================================

CREATE OR REPLACE SECURE VIEW PROTECT360_DB.GOLD.VW_ADVISOR_CUSTOMER_360
    COMMENT = 'Advisor-facing Customer 360 for India — needs-based profile with top NBA action and vulnerability scores'
AS
SELECT
    c.CUSTOMER_ID,
    cust.FULL_NAME,
    c.AGE,
    c.AGE_BAND,
    c.GENDER,
    c.STATE_CODE,
    c.POSTCODE,
    c.SEGMENT_TYPE,
    c.MARKETING_CONSENT_FLAG,
    c.HEALTH_DATA_CONSENT_FLAG,
    c.AADHAAR_VERIFIED_FLAG,
    c.PAN_VERIFIED_FLAG,
    c.CITY_TIER,
    c.ACTIVE_POLICY_COUNT,
    c.IS_UNINSURED,
    c.CURRENT_COVERAGE_STATUS,
    c.CURRENT_COVERAGE_TYPE,
    c.PROTECTION_GAP_FLAG,
    c.TOTAL_ANNUAL_PREMIUM,
    c.HAS_ANY_COVERAGE_FLAG,
    c.INCOME_BAND,
    c.CAPACITY_SCORE,
    c.ITR_FILING_FLAG,
    c.PENSION_INCOME_FLAG,
    c.PMJAY_INCOME_ELIGIBLE,
    c.SOCIOECONOMIC_DECILE,
    c.CONDITION_COUNT,
    c.HAS_DIABETES,
    c.HAS_HYPERTENSION,
    c.HAS_HEART_DISEASE,
    c.LIVING_ALONE_FLAG,
    c.CARE_NEEDS_FLAG,
    c.PREFERRED_SERVICES_RAW,
    c.SURVEY_COMPLETENESS_SCORE,
    c.SURVEY_COMPLETED_FLAG,
    c.CLAIMS_DATA_AVAILABLE,
    c.CLAIM_COUNT_3Y,
    c.CLAIM_AMOUNT_3Y,
    c.HOSPITALIZATION_COUNT_3Y,
    c.HIGH_SEVERITY_CLAIM_FLAG,
    c.CHRONIC_CONDITION_CLAIM_FLAG,
    c.OOP_BURDEN_INR,
    c.COMPLETENESS_SCORE AS DATA_COMPLETENESS_SCORE,
    c.DQ_STATUS AS DATA_QUALITY_STATUS,
    c.VULNERABILITY_SCORE,
    c.GOVT_SCHEME_ELIGIBLE_FLAG,
    c.HIGH_URGENCY_FLAG,
    ROUND(ms.SCORE, 3) AS VULNERABILITY_MODEL_SCORE,
    ms.SCORE_CLASS AS VULNERABILITY_CLASS,
    cat.ACTION_NAME AS TOP_ACTION_NAME,
    nba.FINAL_ACTION_SCORE AS TOP_ACTION_SCORE,
    nba.REASON_TEXT AS TOP_ACTION_REASON,
    nba.ADVISOR_MESSAGE AS TOP_ADVISOR_MESSAGE,
    nba.RECOMMENDED_CHANNEL AS TOP_ACTION_CHANNEL,
    nba.HUMAN_REVIEW_REQUIRED AS TOP_ACTION_NEEDS_REVIEW,
    c.PROFILE_AS_OF_TS
FROM PROTECT360_DB.GOLD.CUSTOMER_360_PROFILE c
LEFT JOIN PROTECT360_DB.SILVER.CUSTOMER cust
    ON c.CUSTOMER_ID = cust.CUSTOMER_ID AND cust.CURRENT_RECORD_FLAG = TRUE
LEFT JOIN PROTECT360_DB.ML.MODEL_SCORE ms
    ON c.CUSTOMER_KEY = ms.CUSTOMER_KEY AND ms.MODEL_KEY = 'VULN_SCORE_V1'
LEFT JOIN PROTECT360_DB.GOLD.NEXT_BEST_ACTION nba
    ON c.CUSTOMER_KEY = nba.CUSTOMER_KEY AND nba.PRIORITY_RANK = 1
LEFT JOIN PROTECT360_DB.GOLD.NBA_ACTION_CATALOG cat
    ON nba.ACTION_KEY = cat.ACTION_KEY;


CREATE OR REPLACE SECURE VIEW PROTECT360_DB.GOLD.VW_EXECUTIVE_OVERVIEW
    COMMENT = 'Executive KPIs for Protect360 India — population health, protection gaps, scheme eligibility'
AS
WITH base AS (
    SELECT * FROM PROTECT360_DB.GOLD.CUSTOMER_360_PROFILE
),
scores AS (
    SELECT CUSTOMER_KEY, SCORE, SCORE_CLASS
    FROM PROTECT360_DB.ML.MODEL_SCORE
    WHERE MODEL_KEY = 'VULN_SCORE_V1' AND CURRENT_SCORE_FLAG = TRUE
)
SELECT
    COUNT(*) AS TOTAL_CUSTOMERS,
    COUNT_IF(b.SEGMENT_TYPE = 'SENIOR_CITIZEN') AS SENIOR_CITIZEN_COUNT,
    COUNT_IF(b.SEGMENT_TYPE = 'GIG_WORKER') AS GIG_WORKER_COUNT,
    COUNT_IF(b.IS_UNINSURED) AS UNINSURED_COUNT,
    ROUND(COUNT_IF(b.IS_UNINSURED) * 100.0 / COUNT(*), 1) AS UNINSURED_PCT,
    COUNT_IF(b.PROTECTION_GAP_FLAG) AS PROTECTION_GAP_COUNT,
    COUNT_IF(b.GOVT_SCHEME_ELIGIBLE_FLAG) AS PMJAY_ELIGIBLE_COUNT,
    ROUND(COUNT_IF(b.GOVT_SCHEME_ELIGIBLE_FLAG) * 100.0 / NULLIF(COUNT_IF(b.IS_UNINSURED), 0), 1) AS PMJAY_ELIGIBLE_OF_UNINSURED_PCT,
    COUNT_IF(s.SCORE_CLASS = 'HIGH') AS HIGH_VULNERABILITY_COUNT,
    COUNT_IF(s.SCORE_CLASS = 'MEDIUM') AS MEDIUM_VULNERABILITY_COUNT,
    COUNT_IF(s.SCORE_CLASS = 'LOW') AS LOW_VULNERABILITY_COUNT,
    ROUND(AVG(b.VULNERABILITY_SCORE), 3) AS AVG_VULNERABILITY_SCORE,
    COUNT_IF(b.HIGH_URGENCY_FLAG) AS HIGH_URGENCY_COUNT,
    COUNT_IF(b.CITY_TIER = 1) AS TIER_1_COUNT,
    COUNT_IF(b.CITY_TIER = 2) AS TIER_2_COUNT,
    COUNT_IF(b.CITY_TIER = 3) AS TIER_3_COUNT,
    COUNT_IF(b.LIVING_ALONE_FLAG) AS LIVING_ALONE_COUNT,
    COUNT_IF(b.CARE_NEEDS_FLAG) AS CARE_NEEDS_COUNT,
    COUNT_IF(b.SURVEY_COMPLETED_FLAG) AS SURVEY_COMPLETED_COUNT,
    ROUND(AVG(b.COMPLETENESS_SCORE), 3) AS AVG_COMPLETENESS_SCORE,
    COUNT_IF(b.DQ_STATUS = 'GREEN') AS DQ_GREEN_COUNT,
    COUNT_IF(b.DQ_STATUS = 'AMBER') AS DQ_AMBER_COUNT,
    COUNT_IF(b.DQ_STATUS = 'RED') AS DQ_RED_COUNT,
    COUNT_IF(b.MARKETING_CONSENT_FLAG) AS MARKETING_CONSENT_COUNT,
    COUNT_IF(b.HEALTH_DATA_CONSENT_FLAG) AS HEALTH_CONSENT_COUNT,
    COUNT_IF(b.CLAIMS_DATA_AVAILABLE) AS CLAIMS_DATA_AVAILABLE_COUNT,
    ROUND(AVG(b.CAPACITY_SCORE), 1) AS AVG_CAPACITY_SCORE,
    ROUND(AVG(b.TOTAL_ANNUAL_PREMIUM), 0) AS AVG_ANNUAL_PREMIUM_INR,
    MAX(b.PROFILE_AS_OF_TS) AS LATEST_PROFILE_REFRESH_TS
FROM base b
LEFT JOIN scores s ON b.CUSTOMER_KEY = s.CUSTOMER_KEY;


CREATE OR REPLACE SECURE VIEW PROTECT360_DB.GOLD.VW_GOVERNANCE_MONITOR
    COMMENT = 'Data quality, consent, and pipeline health monitoring for Protect360 India'
AS
SELECT
    COUNT(*) AS TOTAL_PROFILES,
    COUNT_IF(DQ_STATUS = 'GREEN') AS DQ_GREEN_COUNT,
    COUNT_IF(DQ_STATUS = 'AMBER') AS DQ_AMBER_COUNT,
    COUNT_IF(DQ_STATUS = 'RED') AS DQ_RED_COUNT,
    ROUND(COUNT_IF(DQ_STATUS = 'GREEN') * 100.0 / COUNT(*), 1) AS DQ_GREEN_RATE_PCT,
    ROUND(AVG(COMPLETENESS_SCORE), 3) AS AVG_COMPLETENESS_SCORE,
    ROUND(MIN(COMPLETENESS_SCORE), 3) AS MIN_COMPLETENESS_SCORE,
    ROUND(MAX(COMPLETENESS_SCORE), 3) AS MAX_COMPLETENESS_SCORE,
    COUNT_IF(MARKETING_CONSENT_FLAG) AS MARKETING_CONSENT_COUNT,
    ROUND(COUNT_IF(MARKETING_CONSENT_FLAG) * 100.0 / COUNT(*), 1) AS MARKETING_CONSENT_RATE_PCT,
    COUNT_IF(HEALTH_DATA_CONSENT_FLAG) AS HEALTH_CONSENT_COUNT,
    ROUND(COUNT_IF(HEALTH_DATA_CONSENT_FLAG) * 100.0 / COUNT(*), 1) AS HEALTH_CONSENT_RATE_PCT,
    COUNT_IF(INCOME_BAND IS NOT NULL) AS FINANCIAL_PROFILE_COVERAGE,
    ROUND(COUNT_IF(INCOME_BAND IS NOT NULL) * 100.0 / COUNT(*), 1) AS FINANCIAL_PROFILE_COVERAGE_PCT,
    COUNT_IF(AADHAAR_VERIFIED_FLAG = TRUE) AS AADHAAR_VERIFIED_COUNT,
    ROUND(COUNT_IF(AADHAAR_VERIFIED_FLAG = TRUE) * 100.0 / COUNT(*), 1) AS AADHAAR_VERIFIED_PCT,
    COUNT_IF(PAN_VERIFIED_FLAG = TRUE) AS PAN_VERIFIED_COUNT,
    COUNT_IF(SURVEY_COMPLETED_FLAG = TRUE) AS SURVEY_COMPLETED_COUNT,
    ROUND(COUNT_IF(SURVEY_COMPLETED_FLAG = TRUE) * 100.0 / COUNT(*), 1) AS SURVEY_COVERAGE_PCT,
    COUNT_IF(CLAIMS_DATA_AVAILABLE = TRUE) AS CLAIMS_DATA_COUNT,
    ROUND(COUNT_IF(CLAIMS_DATA_AVAILABLE = TRUE) * 100.0 / COUNT(*), 1) AS CLAIMS_DATA_PCT,
    COUNT_IF(SOCIOECONOMIC_DECILE IS NOT NULL) AS POSTCODE_ENRICHMENT_COVERAGE,
    ROUND(COUNT_IF(SOCIOECONOMIC_DECILE IS NOT NULL) * 100.0 / COUNT(*), 1) AS POSTCODE_ENRICHMENT_PCT,
    COUNT_IF(CAPACITY_SCORE IS NOT NULL) AS CAPACITY_SCORE_COVERAGE,
    MAX(PROFILE_AS_OF_TS) AS LATEST_PROFILE_REFRESH_TS,
    COUNT_IF(INCOME_BAND = 'UNKNOWN') AS INVALID_INCOME_BAND_COUNT
FROM PROTECT360_DB.GOLD.CUSTOMER_360_PROFILE;


CREATE OR REPLACE SECURE VIEW PROTECT360_DB.GOLD.VW_HIGH_PRIORITY_CUSTOMERS
    COMMENT = 'Customers requiring urgent action — high vulnerability, uninsured, living alone, or care needs'
AS
SELECT
    v.CUSTOMER_ID,
    v.FULL_NAME,
    v.AGE,
    v.STATE_CODE,
    v.CITY_TIER,
    v.SEGMENT_TYPE,
    v.INCOME_BAND,
    v.IS_UNINSURED,
    v.PROTECTION_GAP_FLAG,
    v.ACTIVE_POLICY_COUNT,
    v.CURRENT_COVERAGE_STATUS,
    v.CONDITION_COUNT,
    v.LIVING_ALONE_FLAG,
    v.CARE_NEEDS_FLAG,
    v.CLAIMS_DATA_AVAILABLE,
    v.VULNERABILITY_SCORE,
    v.VULNERABILITY_CLASS,
    v.GOVT_SCHEME_ELIGIBLE_FLAG,
    v.PMJAY_INCOME_ELIGIBLE,
    v.CAPACITY_SCORE,
    v.SURVEY_COMPLETED_FLAG,
    v.TOP_ACTION_NAME,
    v.TOP_ACTION_SCORE,
    v.TOP_ACTION_REASON,
    v.TOP_ADVISOR_MESSAGE,
    v.TOP_ACTION_CHANNEL,
    v.DATA_QUALITY_STATUS,
    CASE
        WHEN v.AGE >= 75 AND v.IS_UNINSURED AND v.LIVING_ALONE_FLAG
            THEN 'CRITICAL: Elderly 75+, uninsured, living alone'
        WHEN v.AGE >= 70 AND v.IS_UNINSURED AND v.CONDITION_COUNT >= 2
            THEN 'CRITICAL: 70+, uninsured, multiple health conditions'
        WHEN v.GOVT_SCHEME_ELIGIBLE_FLAG AND v.IS_UNINSURED
            THEN 'PM-JAY eligible but not enrolled — free coverage available'
        WHEN v.VULNERABILITY_SCORE >= 0.70
            THEN 'High vulnerability score (' || ROUND(v.VULNERABILITY_SCORE, 2) || ') — multiple risk factors'
        WHEN v.IS_UNINSURED AND v.AGE >= 60
            THEN 'Senior citizen without any health coverage'
        WHEN v.LIVING_ALONE_FLAG AND v.CARE_NEEDS_FLAG
            THEN 'Living alone with identified care needs'
        WHEN v.IS_UNINSURED AND v.SEGMENT_TYPE = 'GIG_WORKER'
            THEN 'Gig worker without insurance — income at risk'
        ELSE 'Multiple needs factors identified'
    END AS URGENCY_REASON,
    CASE
        WHEN v.AGE >= 75 AND v.IS_UNINSURED AND v.LIVING_ALONE_FLAG THEN 1
        WHEN v.AGE >= 70 AND v.IS_UNINSURED AND v.CONDITION_COUNT >= 2 THEN 1
        WHEN v.GOVT_SCHEME_ELIGIBLE_FLAG AND v.IS_UNINSURED THEN 2
        WHEN v.VULNERABILITY_SCORE >= 0.70 THEN 2
        WHEN v.IS_UNINSURED AND v.AGE >= 60 THEN 3
        WHEN v.LIVING_ALONE_FLAG AND v.CARE_NEEDS_FLAG THEN 3
        WHEN v.IS_UNINSURED AND v.SEGMENT_TYPE = 'GIG_WORKER' THEN 4
        ELSE 5
    END AS URGENCY_TIER
FROM PROTECT360_DB.GOLD.VW_ADVISOR_CUSTOMER_360 v
WHERE v.VULNERABILITY_SCORE >= 0.50
   OR v.GOVT_SCHEME_ELIGIBLE_FLAG = TRUE
   OR (v.LIVING_ALONE_FLAG = TRUE AND v.CARE_NEEDS_FLAG = TRUE)
   OR (v.AGE >= 70 AND v.IS_UNINSURED);
