-- ============================================================
-- ML schema — Feature store and model metadata
-- ============================================================

CREATE TABLE IF NOT EXISTS PROTECT360_DB.ML.DIM_MODEL (
    MODEL_KEY VARCHAR NOT NULL,
    MODEL_ID VARCHAR,
    MODEL_NAME VARCHAR,
    MODEL_TYPE VARCHAR,
    MODEL_VERSION VARCHAR,
    TRAINING_DATE DATE,
    APPROVAL_STATUS VARCHAR,
    DEPLOYMENT_STATUS VARCHAR,
    OWNER VARCHAR,
    DESCRIPTION VARCHAR,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MODEL_KEY)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.ML.MODEL_SCORE (
    MODEL_SCORE_SK VARCHAR NOT NULL,
    CUSTOMER_KEY VARCHAR,
    MODEL_KEY VARCHAR,
    PRODUCT_TYPE VARCHAR,
    SCORE NUMBER(5,4),
    SCORE_CLASS VARCHAR,
    CONFIDENCE NUMBER(5,4),
    FEATURE_SNAPSHOT_TS TIMESTAMP_NTZ,
    SCORING_RUN_TS TIMESTAMP_NTZ,
    VALID_FROM_TS TIMESTAMP_NTZ,
    VALID_TO_TS TIMESTAMP_NTZ,
    CURRENT_SCORE_FLAG BOOLEAN DEFAULT TRUE,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MODEL_SCORE_SK)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.ML.MODEL_SCORE_FACTOR (
    MODEL_SCORE_FACTOR_SK VARCHAR NOT NULL,
    MODEL_SCORE_SK VARCHAR,
    FACTOR_NAME VARCHAR,
    FACTOR_VALUE VARCHAR,
    CONTRIBUTION NUMBER(6,4),
    DIRECTION VARCHAR,
    FACTOR_RANK NUMBER(38,0),
    EXPLANATION VARCHAR,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MODEL_SCORE_FACTOR_SK)
);
