-- ============================================================
-- GOVERNANCE schema — Audit, quality, and consent
-- ============================================================

CREATE TABLE IF NOT EXISTS PROTECT360_DB.GOVERNANCE.PIPELINE_RUN (
    PROCESS_RUN_ID VARCHAR NOT NULL,
    PIPELINE_NAME VARCHAR,
    START_TS TIMESTAMP_NTZ,
    END_TS TIMESTAMP_NTZ,
    STATUS VARCHAR,
    SOURCE_ROW_COUNT NUMBER(38,0),
    LOADED_ROW_COUNT NUMBER(38,0),
    REJECTED_ROW_COUNT NUMBER(38,0),
    ERROR_MESSAGE VARCHAR,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PROCESS_RUN_ID)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.GOVERNANCE.DATA_QUALITY_RESULT (
    DQ_RESULT_ID VARCHAR NOT NULL,
    PROCESS_RUN_ID VARCHAR,
    TABLE_NAME VARCHAR,
    RULE_NAME VARCHAR,
    RULE_TYPE VARCHAR,
    OBSERVED_VALUE NUMBER(10,2),
    THRESHOLD_VALUE NUMBER(10,2),
    STATUS VARCHAR,
    AFFECTED_ROW_COUNT NUMBER(38,0),
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DQ_RESULT_ID)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.GOVERNANCE.CORTEX_RUN (
    CORTEX_RUN_ID VARCHAR NOT NULL,
    PROCESS_RUN_ID VARCHAR,
    FUNCTION_NAME VARCHAR,
    MODEL_NAME VARCHAR,
    PROMPT_VERSION VARCHAR,
    INPUT_RECORD_COUNT NUMBER(38,0),
    SUCCESS_COUNT NUMBER(38,0),
    FAIL_COUNT NUMBER(38,0),
    ESTIMATED_TOKENS NUMBER(38,0),
    STATUS VARCHAR,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CORTEX_RUN_ID)
);
