-- ============================================================
-- SURVEY schema — Person registration (RetireEasy survey app)
-- ============================================================

CREATE SEQUENCE IF NOT EXISTS PROTECT360_DB.SURVEY.PERSON_ID_SEQ
    START WITH 1 INCREMENT BY 1 NOORDER;

CREATE TABLE IF NOT EXISTS PROTECT360_DB.SURVEY.PERSON (
    PERSON_ID VARCHAR(20) NOT NULL,
    FULL_NAME VARCHAR(200) NOT NULL,
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(30),
    NATIONALITY VARCHAR(50),
    MARITAL_STATUS VARCHAR(30),
    STATE_CODE VARCHAR(10),
    POSTCODE VARCHAR(20),
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PERSON_ID)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.SURVEY.PERSON_CONTACT (
    PERSON_ID VARCHAR(20),
    MOBILE_NUMBER VARCHAR(30),
    ALTERNATE_MOBILE VARCHAR(30),
    EMAIL_ADDRESS VARCHAR(200),
    ALTERNATE_EMAIL VARCHAR(200),
    FOREIGN KEY (PERSON_ID) REFERENCES PROTECT360_DB.SURVEY.PERSON(PERSON_ID)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.SURVEY.PERSON_EMPLOYMENT (
    PERSON_ID VARCHAR(20),
    EMPLOYMENT_STATUS VARCHAR(30),
    EMPLOYMENT_TYPE_CODE VARCHAR(30),
    INCOME_FREQUENCY VARCHAR(20),
    COMPANY_ORGANISATION VARCHAR(200),
    JOB_TITLE VARCHAR(200),
    YEARS_OF_EMPLOYMENT NUMBER(5,1),
    WORK_LOCATION VARCHAR(200),
    FOREIGN KEY (PERSON_ID) REFERENCES PROTECT360_DB.SURVEY.PERSON(PERSON_ID)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.SURVEY.PERSON_EMERGENCY_CONTACT (
    PERSON_ID VARCHAR(20),
    CONTACT_NAME VARCHAR(200),
    RELATIONSHIP VARCHAR(50),
    MOBILE_NUMBER VARCHAR(30),
    EMAIL_ADDRESS VARCHAR(200),
    FOREIGN KEY (PERSON_ID) REFERENCES PROTECT360_DB.SURVEY.PERSON(PERSON_ID)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.SURVEY.PERSON_PREFERENCE (
    PERSON_ID VARCHAR(20),
    PREFERRED_LANGUAGE VARCHAR(30),
    PREFERRED_CONTACT_METHOD VARCHAR(20),
    NOTES VARCHAR(2000),
    FOREIGN KEY (PERSON_ID) REFERENCES PROTECT360_DB.SURVEY.PERSON(PERSON_ID)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.SURVEY.PERSON_ADDRESS (
    PERSON_ID VARCHAR(20),
    ADDRESS_LINE_1 VARCHAR(300),
    ADDRESS_LINE_2 VARCHAR(300),
    CITY VARCHAR(100),
    STATE_PROVINCE VARCHAR(100),
    COUNTRY VARCHAR(100),
    POSTAL_ZIP_CODE VARCHAR(20),
    ADDRESS_TYPE VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.SURVEY.PERSON_CONSENT (
    PERSON_ID VARCHAR(20),
    MARKETING_CONSENT_FLAG BOOLEAN,
    HEALTH_DATA_CONSENT_FLAG BOOLEAN
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.SURVEY.PERSON_HEALTH (
    PERSON_ID VARCHAR(20),
    HAS_DIABETES BOOLEAN,
    HAS_HYPERTENSION BOOLEAN,
    HAS_HEART_DISEASE BOOLEAN,
    CONDITION_COUNT NUMBER(5,0),
    LIVING_SITUATION VARCHAR(50),
    LIVING_ALONE_FLAG BOOLEAN,
    CARE_NEEDS_FLAG BOOLEAN
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.SURVEY.PERSON_FINANCIAL (
    PERSON_ID VARCHAR(20),
    INCOME_BAND VARCHAR(20),
    ASSET_BAND VARCHAR(20),
    ITR_FILING_FLAG BOOLEAN,
    PENSION_INCOME_FLAG BOOLEAN,
    TDS_INDICATOR BOOLEAN,
    AADHAAR_VERIFIED_FLAG BOOLEAN,
    PAN_VERIFIED_FLAG BOOLEAN,
    CAPACITY_SCORE NUMBER(3,1)
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.SURVEY.PERSON_INSURANCE (
    PERSON_ID VARCHAR(20),
    CURRENT_COVERAGE_STATUS VARCHAR(30),
    CURRENT_COVERAGE_TYPE VARCHAR(50),
    ACTIVE_POLICY_COUNT NUMBER(5,0),
    TOTAL_ANNUAL_PREMIUM NUMBER(12,2),
    IS_UNINSURED BOOLEAN
);

CREATE TABLE IF NOT EXISTS PROTECT360_DB.SURVEY.PERSON_SERVICE_PREFERENCE (
    PERSON_ID VARCHAR(20),
    WANTS_TELEMEDICINE BOOLEAN,
    WANTS_HOME_VISIT BOOLEAN,
    WANTS_ELDER_CARE BOOLEAN,
    WANTS_FINANCIAL_ADVICE BOOLEAN,
    WANTS_CHECKUP BOOLEAN
);
